baseurl = "http://shirazipooya.github.io"
title = "Pooya Shirazi"

theme = "hugo-coder"

languagecode = "en"

paginate = 100
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "Pooya"

[params]
    author = "Pooya Shirazi"
    description = "Pooya Shirazi's personal website"
    keywords = "Blog, Personal, R, MATLAB"
    info = "PhD in Water Engineering"
    avatarurl = "images/avatar.jpg"
    footercontent = "© 2018 AgroCode, Co."
    
    dateFormat = "2006, Jan 02"

    hideCredits = true
    hideCopyright = true

    rtl = false

    # Custom CSS
    custom_css = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/shirazipooya/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/shirazipooya/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/shirazipooya/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/blog/"
[[menu.main]]
    name = "General Irrigation"
    weight = 2
    url = "/irrigation/"
[[menu.main]]
    name = "Computer Programming"
    weight = 3
    url = "/programming/"
[[menu.main]]
    name = "Upload Your Files"
    weight = 4
    url = "https://shirazipooya.shinyapps.io/uploadfiles/"
